### PR TITLE
fix(client): prevent resource exhaustion from long-lived DNS sessions

### LINKED ISSUE #2679: V 1.19 brake connections in Russia
### Application

Outline Client

### Describe the bug

The latest version of the application is now connecting very fast to the server, but the connection simply doesn’t work on the tough network conditions.
Previous version – that was connecting longer – is rock solid.

### Steps to reproduce

1. Open the app
2. Click connect

### What did you expect to happen?

Connection to happen

### What actually happened?

It stuck

### Outline Version

1.19

### What operation system are you using?

iOS

### Operating System Version

iOS both latest

### Screenshots and Videos

_No response_

### PR DESCRIPTION
**Pull request by fortuna**
DNS is one-shot (one query, one response), but each forwarded DNS query was holding a transport session open until the 30-second write-idle timeout.  Under sustained DNS load this causes session accumulation and eventual resource exhaustion, breaking VPN connectivity.

See [dnsintercept/README.md](https://github.com/OutlineFoundation/outline-apps/blob/fix/dns-session-resource-leak/client/go/outline/dnsintercept/README.md) for the context to help review this PR.

Two fixes:
- forward: close the transport session immediately after delivering the first DNS response, instead of waiting for the idle timeout.
- truncate: create the base transport session lazily, only on the first non-DNS packet.  DNS-only flows never open a base session at all.

Should fix #2679

### CODE REVIEW

File: client/go/outline/dnsintercept/forward.go [hunk 1]
```diff
@@ -49,9 +50,15 @@ type forwardPacketReqSender struct {
...
 }
 
+// forwardPacketRespReceiver intercepts incoming packets from the remote DNS resolver.
+// It remaps the source address from the remote resolver back to the local DNS address,
+// and closes the underlying session after delivering the first DNS response to free the
+// transport session immediately rather than waiting for the idle timeout.
 type forwardPacketRespReceiver struct {
 	network.PacketResponseReceiver
-	fpp *forwardPacketProxy
+	fpp    *forwardPacketProxy
```
Comment (fortuna) [inline client/go/outline/dnsintercept/forward.go]: We should add comments explaining these fields

File: client/go/outline/dnsintercept/truncate.go [hunk 2]
```diff
@@ -29,10 +30,18 @@ type truncatePacketProxy struct {
...
+// truncatePacketReqSender handles packet routing for truncate sessions.
+//
+// DNS packets (destined for local) are handled by trunc and never touch the
+// base proxy.  The base session is created lazily on the first non-DNS packet,
+// avoiding a wasted transport session for DNS-only flows.
 type truncatePacketReqSender struct {
-	network.PacketRequestSender
-	trunc network.PacketRequestSender
-	local netip.AddrPort
+	mu        sync.Mutex
```
Comment (fortuna) [inline client/go/outline/dnsintercept/truncate.go]: We need comments here too.

File: client/go/outline/dnsintercept/truncate.go [hunk 3]
```diff
@@ -57,30 +66,49 @@ func WrapTruncatePacketProxy(base network.PacketProxy, localAddr netip.AddrPort)
...
 // WriteTo checks if the packet is a DNS query to the local intercept address.
-// If so, it truncates the packet. Otherwise, it passes it to the base proxy.
+// If so, it truncates the packet. Otherwise, it passes it to the base proxy,
+// creating the base session on demand if this is the first non-DNS packet.
 func (req *truncatePacketReqSender) WriteTo(p []byte, destination netip.AddrPort) (int, error) {
 	if isEquivalentAddrPort(destination, req.local) {
 		return req.trunc.WriteTo(p, destination)
 	}
-	return req.PacketRequestSender.WriteTo(p, destination)
+	req.mu.Lock()
```
Comment (jyyi1) [inline client/go/outline/dnsintercept/truncate.go:93]: Will the lock cause any performance degradation? Probably use a double-lock pattern?

**Review by jyyi1 — APPROVED** [review]
The code LGTM, with a small performance related comment.

**Comment by ohnorobo** [comment]
rebased off of master to pull in https://github.com/OutlineFoundation/outline-apps/pull/2735

**Comment by ohnorobo** [comment]
rebased again to get https://github.com/OutlineFoundation/outline-apps/pull/2738

File: client/go/outline/dnsintercept/forward.go [hunk 4]
```diff
@@ -19,79 +19,102 @@ import (
...
+		resolverRemoteAddr:    resolverRemoteAddr,
 	}, nil
 }
 
 // NewSession implements PacketProxy.NewSession.
-func (fpp *forwardPacketProxy) NewSession(resp network.PacketResponseReceiver) (_ network.PacketRequestSender, err error) {
-	base, err := fpp.base.NewSession(&forwardPacketRespReceiver{resp, fpp})
+func (fpp *dnsRedirectPacketProxy) NewSession(resp network.PacketResponseReceiver) (_ network.PacketRequestSender, err error) {
+	wrapper := &dnsRedirectPacketRespReceiver{PacketResponseReceiver: resp, fpp: fpp}
+	baseSender, err := fpp.baseProxy.NewSession(wrapper)
```
Comment (fortuna) [inline client/go/outline/dnsintercept/forward.go:83]: I'm skeptical of this `NewSession`. I think we need to do it lazily too, like we are doing for truncate.

But this also made me realize that the layering is probably wrong. We probably want a top level Packet Proxy that dispatches to two PPs: a DNS PP and a "Default" PP.  That way we can share the dispatching and NAT logic.

We may want to borrow the logic from the server: https://github.com/OutlineFoundation/tunnel-server/blob/4d09f750827738d21432095a46e455d24e172109/service/udp.go#L438

Comment (fortuna) [reply client/go/outline/dnsintercept/forward.go:83]: I'm inclined to merge it as is (it's a strict improvement over master), and work on the further fix in a follow up PR.

@ohnorobo @jyyi1 thoughts?

Comment (ohnorobo) [reply client/go/outline/dnsintercept/forward.go:83]: I would also like to get this merged in (we can release in beta to test viability on apple platforms) and then do the further refactoring in a follow up.

**Review by ohnorobo — APPROVED** [review]

**Comment by fortuna** [comment]
I'll follow up with further fixes on another PR

**Comment by ohnorobo** [comment]
This change is likely related to the resource exhaustion crash reported here: https://github.com/OutlineFoundation/outline-apps/issues/2752
